{
  ss,
  pkgs,
  lib,
  config,
  ...
}:
let
  inherit (lib) mkIf mkOption types;
  inherit (lib) pipe filter hasPrefix removePrefix concatStringsSep;
  inherit (lib) assertMsg optional optionalString pathExists foldl' attrValues;

  cfg = config.home.impure;
  hjemUser = config.hjem.users.${config.user.name};
  impureActiveFile = "${config.home.stateDir}/HJEM_IMPURE_ACTIVE";

  hjemFileAttrList = [
    hjemUser.files
    hjemUser.xdg.config.files
    hjemUser.xdg.data.files
    hjemUser.xdg.state.files
    hjemUser.xdg.cache.files
  ];

  planter = pkgs.writeShellApplication {
    name = "hjem-impure";
    runtimeInputs = [
      pkgs.coreutils
    ];
    text = ''
      # Avoid running hjem-impure if system is already impure
      IMPURE_ACTIVE_FILE="${impureActiveFile}"
      if [[ -f "$IMPURE_ACTIVE_FILE" && $(cat "$IMPURE_ACTIVE_FILE") -eq 1 ]]; then
        echo "Re-run not required, already impure."
        echo "See: https://github.com/Rexcrazy804/hjem-impure?tab=readme-ov-file#usage"
        exit 0
      fi

      function symlink() {
        if [[ -e "$2" && ! -L "$2" ]]; then
          echo "$2 exists and is not a symlink. Ignoring it." >&2
          return 0
        fi

        # Remove existing symlink (directory, file, or broken) safely
        if [[ -L "$2" ]]; then
          rm -f "$2"
        elif [[ -d "$2" ]]; then
          rm -rf "$2"
        fi

        mkdir -p "$(dirname "$2")"
        ln -sfv "$1" "$2"
      }

      function replace() {
        if [[ ! -L "$1" ]]; then
          echo "$1 exists and is not a symlink. Ignoring it." >&2
          return 0
        fi
        STORE_PATH=$(realpath "$1")
        rm -f "$1"
        cp -rL --no-preserve=all "$STORE_PATH" "$1"
        chmod -R u+w "$1"
        echo "$1"
      }

      echo "Replacing symlinks with mutable copies..."
      ${
        if replaceFiles == "" then
          "echo 'No files to replace'"
        else
          replaceFiles
      }
    ''
    + (optionalString (cfg.sourceDir != null) ''
      echo ""
      echo "Redirecting symlinks to targetDir..."
      ${
        if symlinkFiles == "" then
          "echo 'No files to symlink'"
        else
          symlinkFiles
      }
    '')
    + ''

      rm -f "$IMPURE_ACTIVE_FILE"
      echo 1 > "$IMPURE_ACTIVE_FILE" || echo "[INFO] Unable to write to $IMPURE_ACTIVE_FILE"
    '';
  };

  # Files belonging to the dotfiles repo -> redirect to local mutable repo
  symlinkFiles = pipe cfg.parseAttrs [
    (filter (x: x ? source && x.source != null && cfg.sourceDir != null && hasPrefix (toString cfg.sourceDir) (toString x.source)))
    (filter (x: assertMsg (pathExists x.source) "hjem-impure: the path ${x.source} DOES NOT EXIST"))
    (map (x: "symlink \"${cfg.targetDir}${removePrefix (toString cfg.sourceDir) (toString x.source)}\" \"${x.target}\""))
    (concatStringsSep "\n")
  ];

  # Other files (e.g. generated by nix) -> copy as mutable normal files
  replaceFiles = pipe cfg.parseAttrs [
    (filter (x: x ? target && x.target != impureActiveFile))
    (filter (x: !(x ? source && x.source != null && cfg.sourceDir != null && hasPrefix (toString cfg.sourceDir) (toString x.source))))
    (map (x: "replace \"${x.target}\""))
    (concatStringsSep "\n")
  ];
in
{
  options.home.impure = {
    enable = lib.mkEnableOption "impure home symlinks redirection";

    sourceDir = lib.mkOption {
      type = types.nullOr (types.either types.path types.str);
      default = "${ss.sourceDir}";
      description = "Nix store immutable snapshot path to redirect away from";
    };
    targetDir = lib.mkOption {
      type = types.str;
      default = config.home.flakeDir;
      description = "Local mutable checkout directory to redirect symlinks to";
    };

    parseAttrs = mkOption {
      type = types.listOf types.attrs;
      default = hjemFileAttrList;
      description = "List of attribute sets to parse files from";
      apply = x: foldl' (acc: curr: acc ++ (attrValues curr)) [ ] x;
    };

    script = mkOption {
      readOnly = true;
      default = planter;
    };
  };

  config = mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.sourceDir != null -> cfg.targetDir != "";
        message = "hjem-impure: `sourceDir` set without setting `targetDir`";
      }
    ];

    warnings = optional (cfg.sourceDir != null && symlinkFiles == "") "hjem-impure: detected zero files to symlink";

    user.packages = [ planter ];

    hjem.users.${config.user.name}.xdg.state.files."HJEM_IMPURE_ACTIVE".text = "0";
  };
}

