keys:
  - &local  age1vdyxye3dfwk530hdr98v9lmwze89yux45ausw75tqdtm25f82a4qf73sdx
  - &server age13e59cm44k84ak9fx2dxwsev0y2a8ld3xuraw0ykh3ejpg5ugc97q6x8nxv
creation_rules:
  - path_regex: hosts/(ss|camel)/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *local
  - path_regex: hosts/hws/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *local
      - *server
  - key_groups:
    - age:
      - *local
 
