keys:
  - &local  age1vdyxye3dfwk530hdr98v9lmwze89yux45ausw75tqdtm25f82a4qf73sdx
  - &server age13e59cm44k84ak9fx2dxwsev0y2a8ld3xuraw0ykh3ejpg5ugc97q6x8nxv
  - &public age1hpwfczthfyk249dgpp29jdwxvqz0q3efeqtvqvypscxpklp3pc6qes2w9m
creation_rules:
  - path_regex: hosts/(ss|camel)/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *local
  - path_regex: hosts/(hws|cts)/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *local
      - *server
  - path_regex: hosts/sis/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *local
      - *public
  - key_groups:
    - age:
      - *local
