keys:
  - &local  age1vdyxye3dfwk530hdr98v9lmwze89yux45ausw75tqdtm25f82a4qf73sdx
  - &server age1kycrkkaq75mtkmyyuu0ccdlm7j0430jqnx907s6cuspwh94nmvcsv93vsq
  # - &public 
creation_rules:
  - path_regex: hosts/(ss|camel)/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *local
  - path_regex: hosts/hwc/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *local
      - *server
  - key_groups:
    - age:
      - *local
 
