{ ss, lib, config, pkgs, ... }:

let
  cfg = config.modules.shell.fish;
in {
  options.modules.shell.fish = with lib; with types; {
    enable          = ss.mkBoolOpt false;
    loginInit       = mkOpt' lines "" "Fish script fragments to run in login shell.";
    interactiveInit = mkOpt' lines "" "Fish script fragments to run in interactive shell.";
    rcFiles         = mkOpt' (listOf (either str path)) [] "List of fish files to source in interactive shell.";
  };

  config = lib.mkIf cfg.enable {
    environment.shells = [ pkgs.fish ];

    home.sessionVariables = {
      NH_FLAKE = config.home.flakeDir;
    };

    programs.fish = {
      enable = true;
      shellAliases = lib.mkForce {};
      shellAbbrs = config.environment.shellAliases;

      loginShellInit = ''
        # Custom modules login hooks
        ${cfg.loginInit}
      '';
    };

    home.configFile = {
      "fish/config.fish".text = ''
        # Load Hjem session variables 
        source "${config.hjem.users.${config.user.name}.environment.loadEnv}"

        # Add user session paths
        ${lib.concatMapStringsSep "\n" (p: "fish_add_path -m '${p}'") config.home.sessionPath}

        # This file was autogenerated by Nix, do not edit it!
        ${lib.optionalString (builtins.pathExists "${ss.configDir}/fish/config.fish")
          ''source "${ss.configDir}/fish/config.fish"''}

        # Local config to debug or test
        test -e $__fish_config_dir/local.fish; and source $__fish_config_dir/local.fish

        # modules.shell.fish.interactiveInit
        ${cfg.interactiveInit}

        # modules.shell.fish.rcFiles
        ${lib.concatMapStringsSep "\n" (f: "test -r '${toString f}'; and source '${toString f}'") cfg.rcFiles}
      '';

      "fish/functions".source = "${ss.configDir}/fish/functions";
      "fish/conf.d".source    = "${ss.configDir}/fish/conf.d";
    };

    user.packages = with pkgs; [
      # CLI core & tools
      coreutils
      fzf
      ripgrep
      tree
      less
      htop
      unzip
      bat
      tlrc
      wget
      curl
      tokei
      fastfetch
      nh
    ];
  };
}
