# # yazi.toml
[manager]
# show_hidden = false
ratio = [1, 2, 4]

[plugin]
deps = [
  { use = "yazi-rs/plugins:full-border", rev = "c7feb90" },
  { use = "yazi-rs/plugins:no-status",   rev = "c7feb90" }
]


